# Generated by Django 4.0.3 on 2022-03-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_products_product_rename_ships_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyavailability',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.booking'),
        ),
        migrations.AlterField(
            model_name='supplyavailability',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.ship'),
        ),
    ]
